function [waveform,transmitter,radiator,collector,receiver,sensormotion,...
    target,tgtmotion,channel,matchedfilter,tvg,threshold,clutter] = ...
    helperDelayLineSpinningTargetSetup(fs,pw,prf,fc,c,txSpec,tgtSpec,clutterSpec)
    
    pri = 1/prf;
    waveform = phased.RectangularWaveform(...
    'SampleRate',fs,'PulseWidth',pw,...
    'PRF',prf);


    transmitter = phased.Transmitter(...
    'PeakPower',txSpec.peakPower,'InUseOutputPort',true);
    
    radiator = phased.Radiator(...
    'Sensor',phased.IsotropicAntennaElement,...
    'PropagationSpeed',c,'OperatingFrequency',fc);

    collector = phased.Collector(...
    'Sensor',phased.IsotropicAntennaElement,...
    'PropagationSpeed',c,'OperatingFrequency',fc);

    receiver = phased.ReceiverPreamp(...
    'SampleRate',fs,'EnableInputPort',true);

    sensormotion = phased.Platform('InitialPosition',[0,0,txSpec.height]');

    tgtmotion = phased.Platform('InitialPosition',tgtSpec.pos,'VelocitySource','Input port');

    target = phased.RadarTarget(...
        'MeanRCS',tgtSpec.rcs,'PropagationSpeed',c,'OperatingFrequency',fc);

    channel = phased.FreeSpace(...
    'PropagationSpeed',c,'OperatingFrequency',fc,...
    'TwoWayPropagation',true,'SampleRate',fs);

    match_sig = getMatchedFilter(waveform);
    matchedfilter =  phased.MatchedFilter(...
        'Coefficients',match_sig);
    fast_time_grid = 0:1/fs:1/prf-1/fs;
    range_gates = c*fast_time_grid/2;
    max_range = 8e3;
    lambda = c/fc;

    rng_loss = 2*fspl(range_gates,lambda);
    ref_loss = 2*fspl(max_range,lambda);   

    tvg = phased.TimeVaryingGain(...
        'RangeLoss',rng_loss,...
        'ReferenceLoss',ref_loss);
    
    clutter   = constantGammaClutter('Sensor',collector.Sensor,...
    'PropagationSpeed',radiator.PropagationSpeed,...
    'OperatingFrequency',radiator.OperatingFrequency,...
    'SampleRate',waveform.SampleRate,'TransmitSignalInputPort',true,...
    'PRF',waveform.PRF,'Gamma',clutterSpec.gamma,'PlatformHeight',txSpec.height,...
    'PlatformSpeed',0,'PlatformDirection',[0;0],...
    'MountingAngles',[0 0 0],'ClutterMaxRange',5000,...
    'ClutterAzimuthSpan',clutterSpec.azimuthSpan,'PatchAzimuthSpan',clutterSpec.patchAzimuthSpan,...
    'SeedSource','Property','Seed',2011);

    threshold = 4e-11;



end

